apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-backend
  labels:
    app: taskboard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard-backend
  template:
    metadata:
      labels:
        app: taskboard-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: taskboard-backend
          image: taskboard-backend:1.0.5
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
