apiVersion: v1
kind: Service
metadata:
  name: taskboard-backend-service
spec:
  type: NodePort
  selector:
    app: taskboard-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
